name: Release TIC-80 Pakz
on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-26.04-arm
    container: ghcr.io/loveretro/${{ matrix.target }}-toolchain:main
    strategy:
      matrix:
        target:
          - tg5040
          - tg5050
          - my355
          - h700
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Clone TIC-80
        run: git clone --branch v1.2.0 --single-branch --recursive https://github.com/nesbox/TIC-80
      - name: Build
        working-directory: ./TIC-80
        run: |
          cmake -B build -DBUILD_LIBRETRO=ON -DBUILD_STATIC=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_PLAYER=OFF -DBUILD_SDL=OFF -DBUILD_WITH_ALL=ON -DBUILD_WITH_RUBY=OFF
          cmake --build build --parallel
          aarch64-nextui-linux-gnu-strip --strip-unneeded build/bin/tic80_libretro.so
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        if: github.ref_type == 'tag'
        with:
          name: artifact-${{ matrix.target }}
          path: TIC-80/build/bin/tic80_libretro.so
  release:
    name: Release
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-26.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Download all artifacts
        uses: actions/download-artifact@v8
      - name: Create Package
        run: |
          for target in tg5040 tg5050 my355 h700; do
            directory="Emus/$target/TIC.pak"
            mkdir -p "$directory"
            cp default.cfg launch.sh "artifact-$target/tic80_libretro.so" "$directory"
          done
          zip -r TIC.pakz Emus
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: TIC.pakz
